### ISSUE TITLE
Support SAML from Jasig CAS?

### ISSUE THREAD

**Issue by samrocketman** [dlindahl/omniauth-cas#22]
Currently SAML is supported in the Jasig version of CAS.  Can you update the library to support that?

It looks like where you got the omniauth-cas originally there is some SAML implementation but I don't know enough ruby to make it work.

This would be greatly appreciated if you could.  I can provide SAML auth samples if you like for test fixtures.

SAM

**Comment by lucasperin** [comment]
+1
Can anyone share their workarounds for SAML validation with gitlab?
