### ISSUE TITLE
Next release — 2.0.0?

### ISSUE THREAD

**Issue by danschmidt5189** [dlindahl/omniauth-cas#53]
After merging #51 it's time to bump the release. That fix passes an additional argument to the `fetch_raw_info` callback, which breaks anyone using a Lambda. The README suggested using a lambda prior to that (I amended it to use a bare Proc), so I think it's reasonable for users to see this as a breaking change, implying a major version bump from the current v1.1.1 to a new v2.0.0.

Questions / comments / thoughts / concerns?

**Comment by vjt** [comment]
Agree.

**Comment by vjt** [comment]
v2.0.0 has been pushed to Ruby Gems today 2020-11-14.

Cheers!
