### ISSUE TITLE
can't use omniauth-cas within gitlab

### ISSUE THREAD

**Issue by moobyfr** [dlindahl/omniauth-cas#7]
Hi
Using several modules in gitlab for auth such as ldap, or omniauth-google-oauth2 works fine.
But If  I use omniauth-cas (1.0.1), I get a backtrace:

omniauth:
  enabled: true
  allow_single_sign_on: false
  block_auto_created_users: true
  providers:
      - { name: 'cas',   host: 'cas.XXX.tld', login_url: 'cas/login/' }

==> unicorn.stderr.log <==
/usr/local/lib/ruby/gems/1.9.1/gems/omniauth-1.1.1/lib/omniauth/strategy.rb:136:in `initialize': Received wrong number of arguments. [nil, nil] (ArgumentError)
        from /usr/local/lib/ruby/gems/1.9.1/gems/omniauth-cas-1.0.1/lib/omniauth/strategies/cas.rb:58:in`initialize'
        from /usr/local/lib/ruby/gems/1.9.1/gems/actionpack-3.2.9/lib/action_dispatch/middleware/stack.rb:43:in `new'

Is the error in omniauth-cas ?

**Comment by moobyfr** [comment]
Hi
I'm the author of the initial issue.
The error as described doesn't show anymore with gitlab 7 (+onmiauth-cas 1.0.4), but there is still a issue:
Gitlab requires at least two entries: email and user. In a basic CAS server, the response has only the user in response. If the CAS server is configured to transmit more entries, they are stored by omniauth-cas .

Forcing to reply with a fixed email makes this omniauth module operational.

It seems that the parameter fetch_raw_info could be a solution to force an email (I would prefer to be able to call the omniauth-ldap module to retrieve the ldap attributes, but I don't know enough ruby for now)

**Comment by dlindahl** [comment]
I no longer have access to a CAS server and therefore am no longer fit to maintain this project.

If you would like to volunteer to be a maintainer of this project, please let me know by opening an Issue.

**Comment by skywalkerjc** [comment]
I try to add onmiauth-cas 1.1.0 to my gitlab-v8.8.0 with `gem install onmiauth-cas,` and I exactlly folowed Installation, I add
 ```
Rails.application.config.middleware.use OmniAuth::Builder do
  provider :cas, host: 'cas.yourdomain.com'
end
```
to gitlab/config/initializers/omniauth.rb  but run error 
```Refreshing Gem list
Devise::OmniAuth::StrategyNotFound: Could not find a strategy with name `Cas'. Please ensure it is required or explicitly set it using the :strategy_class option```

then I tried to follow https://github.com/gitlabhq/gitlab-public-wiki/wiki/Custom-omniauth-provider-configurations
add ```config.omniauth :cas, url: 'https://sso.example.com/', disable_ssl_verification: false```
to gitlab/config/initializers/devise.rb , but the same errot info, is there any thing I miss out, please help me. Thx

**Comment by danschmidt5189** [comment]
Works fine with our GitLab 11.x instance. Closing — reopen if there's interest and test cases.
